### ISSUE TITLE
"Minimal or complete" UniProte and GENCODE proteomes

### ISSUE THREAD

**Issue by trishorts** [sheynkman-lab/Long-Read-Proteogenomics#9]
Just wondering if we'll be limiting the uniprot and gencode protoeomes to include only those genes observed in pac bio. I don't know that we should. If fact, there is some reason not to limit them. But, i'd be glad to see this topic discussed.

**Comment by rmmiller22** [comment]
The plan as it stands is to not limit the UniProt and GENCODE proteomes, but to acknowledge there are going to Proteins identified searching these databases that are not in our PacBio database likely because of one of the following reasons: they result from transcripts that are too short to be sequenced by PacBio (removed in sample preparation), they result from transcripts that are too long to be accurately sequenced by PacBio (for example Titan), or they did not meet our filtering criteria (some of that could be due to only having sequencing data from one cell which is totally fine as long as we acknowledge it). One of the purposes of looking at the 6-frame translation database is to see which transcripts were sequenced by PacBio but did not make the cut for the final database.

**Comment by trishorts** [comment]
will we use uniprot with isoforms or without? with might make sense since we really are interested in isoforms (not genes) and uniprot has annotated isoforms.

I don't know if genecode has anything equivalent.

**Comment by rmmiller22** [comment]
With isoforms in UniProt and the equivalent for GENCODE will be used. That way we can see if PacBio is identifying any isoforms that are not found in either of those reference databases.

**Comment by rmmiller22** [comment]
For UniProt the plan was to use the Reviewed sequences canonical and isoform fasta

**Comment by gsheynkman** [comment]
Closing this issue
